[package]
name = "pars"
version = "0.1.0"
edition = "2021"
description = "Приклад парс крейту"
authors = ["Tikhon Ishchenko"]
license = "MIT"

[dependencies]
anyhow = "1.0.91"

pest = "2.1"

pest_derive = "2.1"
